export const apiUrl = "http://localhost:3000/api/v1"

export const REQUEST_LOGIN_ACCOUNT ="REQUEST_LOGIN_ACCOUNT"
export const LOGIN_ACCOUNT_SUCCESS = "LOGIN_ACCOUNT_SUCCESS";
export const LOGIN_ACCOUNT_FAIL = "LOGIN_ACCOUNT_FAIL";

export const REQUEST_REGISTER_ACCOUNT = "REQUEST_REGISTER_ACCOUNT";
export const REGISTER_ACCOUNT_SUCCESS = "REGISTER_ACCOUNT_SUCCESS";
export const REGISTER_ACCOUNT_FAIL = "REGISTER_ACCOUNT_FAIL";

