export const apiUrl = "http://localhost:3000/api/v1"

export const REQUEST_LOGIN_ACCOUNT ="REQUEST_LOGIN_ACCOUNT"
export const LOGIN_ACCOUNT_SUCCESS = "LOGIN_ACCOUNT_SUCCESS";
export const LOGIN_ACCOUNT_FAIL = "LOGIN_ACCOUNT_FAIL";

export const REQUEST_REGISTER_ACCOUNT = "REQUEST_REGISTER_ACCOUNT";
export const REGISTER_ACCOUNT_SUCCESS = "REGISTER_ACCOUNT_SUCCESS";
export const REGISTER_ACCOUNT_FAIL = "REGISTER_ACCOUNT_FAIL";

export const ADMIN_REQUEST_ADD_TASK ="REQUEST_LOGIN_ACCOUNT";
export const ADMIN_ADD_TASK_SUCCESS = "ADMIN_ADD_TASK_SUCCESS";
export const ADMIN_ADD_TASK_FAIL = "ADMIN_ADD_TASK_FAIL";

export const REQUEST_GET_ALL_USERS ="REQUEST_GET_ALL_USERS";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const REQUEST_GET_ALL_TASKS_ASSIGNED = "REQUEST_GET_ALL_TASKS_ASSIGNED";
export const GET_ALL_TASKS_ASSIGNED_SUCCESS = "GET_ALL_TASKS_ASSIGNED_SUCCESS";
export const GET_ALL_TASKS_ASSIGNED_FAIL = "GET_ALL_TASKS_ASSIGNED_FAIL";

export const REQUEST_GET_ALL_TASKS_NOT_ASSIGNED = "REQUEST_GET_ALL_TASKS_NOT_ASSIGNED";
export const GET_ALL_TASKS_NOT_ASSIGNED_SUCCESS = "GET_ALL_TASKS_NOT_ASSIGNED_SUCCESS";
export const GET_ALL_TASKS_NOT_ASSIGNED_FAIL = "GET_ALL_TASKS_NOT_ASSIGNED_FAIL";

export const GET_TASK_INFOS = "GET_TASK_INFOS";

export const ADMIN_ASSIGN_TASK = "ADMIN_ASSIGN_TASK";